services:
  # ==========================================================
  # 🗄️ SQL SERVER DATABASE (private)
  # ==========================================================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    ports:
      - "1433:1433"    # still exposed for SSMS local debugging only
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # ==========================================================
  # ⚙️ BACKEND API (.NET 8 – WeatherApp)
  # ==========================================================
  backend-api:
    build:
      context: ../Weather Project on DevelopmentServer/Backend
      dockerfile: Dockerfile
    container_name: backend-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=WeatherDB;User ID=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5000:8080"
    networks:
      - backend-network
      - frontend-network
    restart: always

  # ==========================================================
  # 🌐 FRONTEND (NGINX STATIC WEB)
  # ==========================================================
  frontend:
    build:
      context: ../Weather Project on DevelopmentServer/Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-api
    networks:
      - frontend-network
    restart: always

# ==========================================================
# 🌉 NETWORK DEFINITIONS (Isolation)
# ==========================================================
networks:
  frontend-network:
    driver: bridge   # public-facing network (frontend ↔ backend)
  backend-network:
    driver: bridge   # private internal network (backend ↔ database)

# ==========================================================
# 💾 VOLUMES
# ==========================================================
volumes:
  sql_data:
